# Generated by Django 5.0.6 on 2024-06-06 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0002_staff_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=8),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Adminapp.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Adminapp.district'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=8),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_number',
            field=models.CharField(default=1, max_length=155),
        ),
    ]
