# Generated by Django 5.0.6 on 2024-06-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0003_district_state_driver_status_driver_vehicle_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=8),
        ),
    ]
