# Generated by Django 5.0.6 on 2024-06-06 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0004_district_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='district',
            new_name='district_name',
        ),
    ]
