# Generated by Django 5.0.6 on 2024-06-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0005_rename_district_vehicle_district_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='district_name',
        ),
    ]
