# Generated by Django 5.0.6 on 2024-06-07 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0006_remove_vehicle_district_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='vehicle_number',
        ),
    ]
