# Generated by Django 5.0.6 on 2024-06-07 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0008_designation_alter_staff_designation'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='designation',
            table='designations_table',
        ),
    ]
