# Generated by Django 5.0.6 on 2024-06-07 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0009_alter_designation_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'designations_table',
            },
        ),
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.designations'),
        ),
        migrations.DeleteModel(
            name='Designation',
        ),
    ]
