# Generated by Django 5.0.6 on 2024-06-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0010_designations_alter_staff_designation_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='designations',
            table='job_table',
        ),
    ]
