# Generated by Django 5.0.6 on 2024-06-12 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0012_designation_alter_staff_designation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'state_table',
            },
        ),
        migrations.AlterField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.state'),
        ),
    ]
