# Generated by Django 5.0.6 on 2024-06-12 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0013_state_alter_district_state'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='state',
            table='s_table',
        ),
    ]
