# Generated by Django 5.0.6 on 2024-06-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0014_alter_state_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='state',
            table='state_table',
        ),
    ]
