# Generated by Django 5.0.6 on 2024-06-12 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0015_alter_state_state_alter_state_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'states_table',
            },
        ),
        migrations.AlterField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.states'),
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
