# Generated by Django 5.0.6 on 2024-06-12 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0016_states_alter_district_state_delete_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sta',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'sta_table',
            },
        ),
        migrations.AlterField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.sta'),
        ),
        migrations.DeleteModel(
            name='States',
        ),
    ]
