# Generated by Django 5.0.6 on 2024-06-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0017_sta_alter_district_state_delete_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='state',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='staff',
            name='user_name',
            field=models.CharField(default=1, max_length=150),
        ),
        migrations.DeleteModel(
            name='Sta',
        ),
    ]
