# Generated by Django 5.0.6 on 2024-06-13 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0018_alter_district_state_staff_user_name_delete_sta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='user_name',
            new_name='username',
        ),
    ]
