# Generated by Django 5.0.6 on 2024-06-13 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0019_rename_user_name_staff_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='username',
        ),
    ]
