# Generated by Django 5.0.6 on 2024-06-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0020_remove_staff_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='designation_name',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
