# Generated by Django 5.0.6 on 2024-07-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0021_staff_designation_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('ledger_id', models.AutoField(primary_key=True, serialize=False)),
                ('ledger_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'ledger_table',
            },
        ),
    ]
