# Generated by Django 5.0.6 on 2024-06-03 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('date', models.DateField()),
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('consignee_address', models.CharField(max_length=200)),
                ('number_of_boxes', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('price', models.IntegerField()),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.consignee')),
                ('consignor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.consignor')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.district')),
            ],
            options={
                'db_table': 'booking_table',
            },
        ),
        migrations.CreateModel(
            name='Despatch',
            fields=[
                ('date', models.DateField()),
                ('despatch_id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_name', models.CharField(max_length=200)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staffapp.booking')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.district')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.vehicle')),
            ],
            options={
                'db_table': 'despatch_table',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('date', models.DateField()),
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Delivered', 'Delivered'), ('Returned', 'Returned')], default='Returned', max_length=9)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staffapp.booking')),
                ('despatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staffapp.despatch')),
            ],
            options={
                'db_table': 'delivery_table',
            },
        ),
    ]
