# Generated by Django 5.0.6 on 2024-06-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staffapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
