# Generated by Django 5.0.6 on 2024-06-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staffapp', '0002_booking_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='consignor_name',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
