# Generated by Django 5.0.6 on 2024-06-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staffapp', '0003_booking_consignor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='consignee_name',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='district_name',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
