# Generated by Django 5.0.6 on 2024-06-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staffapp', '0004_booking_consignee_name_booking_district_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='despatch',
            name='vehicle_name',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
