# Generated by Django 5.0.6 on 2024-06-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staffapp', '0006_remove_despatch_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
