# Generated by Django 5.0.6 on 2024-06-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staffapp', '0007_booking_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despatch',
            name='booking',
        ),
        migrations.AddField(
            model_name='despatch',
            name='booking',
            field=models.ManyToManyField(to='Staffapp.booking'),
        ),
    ]
