# Generated by Django 5.0.6 on 2024-06-27 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staffapp', '0008_remove_despatch_booking_despatch_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='despatch',
            old_name='booking',
            new_name='bookings',
        ),
    ]
