# Generated by Django 5.0.6 on 2024-06-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staffapp', '0010_booking_status_delivery_consignee_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='despatch',
        ),
    ]
