# Generated by Django 5.0.6 on 2024-07-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staffapp', '0011_remove_delivery_despatch_booking_status'),
    ]

    operations = [

    ]
