# Generated by Django 5.0.6 on 2024-07-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staffapp', '0012_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despatch',
            name='bookings',
        ),

    ]
