# Generated by Django 5.0.6 on 2024-07-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staffapp', '0013_remove_despatch_bookings_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='despatch',
            name='bookings',
            field=models.ManyToManyField(to='Staffapp.booking'),
        )
    ]
