# Generated by Django 5.0.7 on 2024-08-08 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staffapp', '0014_booking_status_despatch_bookings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receipt_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staffapp.booking')),
            ],
            options={
                'db_table': 'receipt_table',
            },
        ),
    ]
